# Generated by Django 4.0.3 on 2022-04-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(height_field='400', upload_to='product_image', verbose_name='Product_image', width_field='400'),
        ),
    ]
