# Generated by Django 4.0.3 on 2022-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0005_cart_price_alter_cart_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_address',
            field=models.BooleanField(default=False),
        ),
    ]
