# Generated by Django 4.0.3 on 2022-04-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0006_customer_add_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=30, null=True, verbose_name='Email address'),
        ),
    ]
