# Generated by Django 4.0.3 on 2022-04-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0007_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, verbose_name='Order date'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('On the way', 'On the way'), ('shipped', 'shipped'), ('Out for delievery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=30, verbose_name='Status'),
        ),
    ]
