# Generated by Django 4.0.3 on 2022-04-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0008_alter_orderplaced_ordered_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(auto_created=True, verbose_name='Order date'),
        ),
    ]
