# Generated by Django 4.0.3 on 2022-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0009_alter_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='ordered_date',
            field=models.DateField(verbose_name='Order date'),
        ),
    ]
