# Generated by Django 4.0.3 on 2022-04-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0010_alter_orderplaced_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Order placed', 'Order placed'), ('On the way', 'On the way'), ('shipped', 'shipped'), ('Out for delievery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], default='Order placed', max_length=30, verbose_name='Status'),
        ),
    ]
