# Generated by Django 4.0.3 on 2022-05-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0012_remove_orderplaced_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ship_diff',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='shipping_address',
        ),
    ]
