# Generated by Django 4.0.3 on 2022-05-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0014_remove_customer_add_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='add_count',
            field=models.SmallIntegerField(default=0, verbose_name='Address count'),
        ),
    ]
