# Generated by Django 4.0.3 on 2022-05-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0015_customer_add_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buycomapp.customer', verbose_name='Adddress Details'),
        ),
    ]
