# Generated by Django 4.0.3 on 2022-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycomapp', '0016_orderplaced_address_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_amount',
            field=models.FloatField(default=0, verbose_name='Total amount'),
        ),
    ]
