version: '3.8'

services:
  buycom:
    build: .
    container_name: buycom
    command: gunicorn buycom.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/buycom
    ports:
      - "8000:8000"
